name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.2'

    - name: Enable bundler cache
      uses: actions/cache@v4
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Install dependencies
      run: |
        gem install bundler -v 2.5.10
        bundle config set --local path 'vendor/bundle'
        bundle install --jobs 4 --retry 3
        gem update --system 3.2.28 --no-document
        bundle update --bundler
        npm install -g mermaid.cli

    - name: Update uri gem
      run: bundle update uri

    - name: Setup deploy options
      id: setup
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        if [[ ${GITHUB_REF} = refs/pull/*/merge ]]; then # pull request
          echo "SRC_BRANCH=${GITHUB_HEAD_REF}" >> "$GITHUB_OUTPUT"
          echo "NO_PUSH=--no-push" >> "$GITHUB_OUTPUT"
        elif [[ ${GITHUB_REF} = refs/heads/* ]]; then # branch, e.g. master, source etc
          echo "SRC_BRANCH=${GITHUB_REF#refs/heads/}" >> "$GITHUB_OUTPUT"
        fi
        echo "DEPLOY_BRANCH=gh-pages" >> "$GITHUB_OUTPUT"

    - name: Deploy website
      run: |
        bundle exec jekyll clean # Ensure a clean state
        bundle exec jekyll build
        yes | bin/deploy --verbose ${{ steps.setup.outputs.NO_PUSH }} \
                    --src ${{ steps.setup.outputs.SRC_BRANCH }} \
                    --deploy ${{ steps.setup.outputs.DEPLOY_BRANCH }}
